version: "3.7"

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_node
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"